/** Clerk UI — seamless marketplace canvas, no card chrome */
export const clerkAppearance = {
  variables: {
    colorPrimary: "#0a0a0a",
    colorDanger: "#0a0a0a",
    colorSuccess: "#0a0a0a",
    colorWarning: "#3a3a3a",
    colorNeutral: "#0a0a0a",
    colorText: "#0a0a0a",
    colorTextSecondary: "rgba(10, 10, 10, 0.45)",
    colorTextOnPrimaryBackground: "#f7f7f5",
    colorBackground: "transparent",
    colorInputBackground: "transparent",
    colorInputText: "#0a0a0a",
    colorBorder: "rgba(10, 10, 10, 0.12)",
    colorMutedForeground: "rgba(10, 10, 10, 0.35)",
    borderRadius: "0px",
    fontFamily: "var(--font-montreal), NeueMontreal, Arial, sans-serif",
    fontFamilyButtons: "var(--font-montreal), NeueMontreal, Arial, sans-serif",
    fontSize: "15px",
    fontWeight: {
      normal: 500,
      medium: 500,
      bold: 500,
    },
  },
  elements: {
    rootBox: "w-full bg-transparent",
    cardBox: "w-full bg-transparent shadow-none",
    card: "w-full border-0 bg-transparent p-0 shadow-none",
    main: "bg-transparent gap-5",
    header: "hidden",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    logoBox: "hidden",
    logoImage: "hidden",
    socialButtons: "gap-3",
    socialButtonsBlockButton:
      "h-12 border-0 border-b border-black/15 bg-transparent px-0 text-[13px] font-medium uppercase tracking-[0.12em] text-black shadow-none hover:border-black",
    socialButtonsBlockButtonText: "font-medium",
    socialButtonsProviderIcon: "opacity-70",
    dividerRow: "my-1",
    dividerLine: "bg-black/[0.08]",
    dividerText: "text-[11px] uppercase tracking-[0.16em] text-black/30",
    form: "gap-5",
    formFieldRow: "gap-1",
    formFieldLabel:
      "text-[11px] font-medium uppercase tracking-[0.16em] text-black/35",
    formFieldInput:
      "h-12 border-0 border-b border-black/15 bg-transparent px-0 text-[15px] text-black shadow-none outline-none ring-0 focus:border-black focus:shadow-none focus:ring-0",
    formFieldInputShowPasswordButton: "text-black/35 hover:text-black",
    formButtonPrimary:
      "mt-2 h-12 bg-black text-[12px] font-medium uppercase tracking-[0.16em] text-white shadow-none hover:opacity-80",
    footer: "hidden bg-transparent",
    footerAction: "hidden",
    footerActionLink: "hidden",
    footerActionText: "hidden",
    footerPages: "hidden",
    identityPreview: "border-0 border-b border-black/10 bg-transparent px-0",
    identityPreviewText: "text-[14px] text-black",
    identityPreviewEditButton: "text-black/40 hover:text-black",
    otpCodeFieldInput:
      "border-0 border-b border-black/15 bg-transparent text-black focus:border-black",
    alternativeMethodsBlockButton:
      "border-0 border-b border-black/15 bg-transparent px-0 text-[13px] text-black hover:border-black",
    alert: "bg-transparent px-0 shadow-none",
    alertText: "text-[13px] text-black/55",
    formFieldErrorText: "text-[12px] text-black/50",
    formFieldSuccessText: "text-[12px] text-black/50",
    navbar: "hidden",
    scrollBox: "bg-transparent",
  },
  layout: {
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    showOptionalFields: false,
  },
};
