/** Clerk UI — calm marketplace chrome, tight form rhythm */
export const clerkAppearance = {
  variables: {
    colorPrimary: "#0a0a0a",
    colorDanger: "#0a0a0a",
    colorSuccess: "#0a0a0a",
    colorWarning: "#3a3a3a",
    colorNeutral: "#0a0a0a",
    colorText: "#0a0a0a",
    colorTextSecondary: "rgba(10, 10, 10, 0.45)",
    colorTextOnPrimaryBackground: "#f7f7f5",
    colorBackground: "transparent",
    colorInputBackground: "#f7f7f5",
    colorInputText: "#0a0a0a",
    colorBorder: "rgba(10, 10, 10, 0.14)",
    colorMutedForeground: "rgba(10, 10, 10, 0.35)",
    borderRadius: "0px",
    fontFamily: "var(--font-montreal), NeueMontreal, Arial, sans-serif",
    fontFamilyButtons: "var(--font-montreal), NeueMontreal, Arial, sans-serif",
    fontSize: "14px",
    spacingUnit: "0.8rem",
    fontWeight: {
      normal: 500,
      medium: 500,
      bold: 500,
    },
  },
  elements: {
    rootBox: "w-full !bg-transparent",
    cardBox: "w-full !bg-transparent !shadow-none !p-0 !rounded-none",
    card: "w-full !border-0 !bg-transparent !p-0 !shadow-none !rounded-none",
    main: "!gap-3.5 !bg-transparent",
    header: "!hidden",
    headerTitle: "!hidden",
    headerSubtitle: "!hidden",
    logoBox: "!hidden",
    logoImage: "!hidden",
    socialButtons: "!gap-2",
    socialButtonsBlockButton:
      "!h-11 !rounded-none !border !border-black/12 !bg-transparent !px-4 !text-[11px] !font-medium !uppercase !tracking-[0.12em] !text-black !shadow-none hover:!border-black hover:!bg-black hover:!text-white",
    socialButtonsBlockButtonText: "!font-medium",
    socialButtonsProviderIcon: "!opacity-70",
    dividerRow: "!my-4",
    dividerLine: "!bg-black/[0.08]",
    dividerText: "!text-[10px] !uppercase !tracking-[0.18em] !text-black/30",
    form: "!gap-3.5",
    formFieldRow: "!gap-1.5",
    formFieldLabelRow: "!mb-1.5",
    formFieldLabel:
      "!text-[10px] !font-medium !uppercase !tracking-[0.16em] !text-black/35",
    formFieldInput:
      "!h-11 !rounded-none !border !border-black/12 !bg-transparent !px-3.5 !text-[14px] !text-black !shadow-none !outline-none focus:!border-black focus:!shadow-none focus:!ring-0",
    formFieldInputShowPasswordButton: "!text-black/35 hover:!text-black",
    formFieldAction: "!text-[11px] !text-black/40 hover:!text-black",
    formButtonPrimary:
      "!mt-0.5 !h-11 !rounded-none !bg-black !text-[11px] !font-medium !uppercase !tracking-[0.16em] !text-white !shadow-none hover:!opacity-80",
    footer: "!hidden",
    footerAction: "!hidden",
    footerActionLink: "!hidden",
    footerActionText: "!hidden",
    footerPages: "!hidden",
    identityPreview:
      "!border !border-black/12 !bg-transparent !px-3.5 !py-2.5 !rounded-none !shadow-none",
    identityPreviewText: "!text-[13px] !text-black",
    identityPreviewEditButton: "!text-black/40 hover:!text-black",
    otpCodeFieldInput:
      "!border !border-black/12 !bg-transparent !text-black focus:!border-black !rounded-none",
    alternativeMethodsBlockButton:
      "!border !border-black/12 !bg-transparent !text-[12px] !text-black hover:!border-black !rounded-none !shadow-none",
    alert: "!bg-transparent !px-0 !shadow-none",
    alertText: "!text-[12px] !text-black/50",
    formFieldErrorText: "!text-[11px] !text-black/50",
    formFieldSuccessText: "!text-[11px] !text-black/50",
    navbar: "!hidden",
    scrollBox: "!bg-transparent !shadow-none",
  },
  layout: {
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    showOptionalFields: false,
  },
  options: {
    unsafe_disableDevelopmentModeWarnings: true,
  },
};
